Feature/bjorn - dao testemployee
GradinIT/ProgrammingForTesters pull request #206
Opened 2021-12-02 14:38 UTC by bjornbonnevier

dao

testemployeedao
testemployeedatabaseentry
testemployeedatabaseentrymapper

2021-12-02 14:51 UTC, kasiasowinska approved these changes

2021-12-02 16:42 UTC, FredrikaAr approved these changes

2021-12-02 18:56 UTC, anitas21 requested changes
TestEmployeeDatabaseEntry behöver mer jobb..
 
jag gjorde en checkout på feature/bjorn och körde 
 
Expected :EmployeeDatabaseEntry(employeeId=2, firstName=Test/QA, lastName=SQUARE1, salary=50000, fullTime=true, departmentId=5)
Actual   :EmployeeDatabaseEntry(employeeId=2, firstName=Test/QA, lastName=null, salary=null, fullTime=null, departmentId=null)

2021-12-03 13:53 UTC, anitas21 approved these changes

2021-12-03 13:53 UTC, MikaelKarlsson91 approved these changes

2021-12-03 13:55 UTC, merged

2021-12-03 14:44 UTC, SugathriSistla reviewed
> 😊